"""Tests for parallax refine command."""

from pathlib import Path
from unittest.mock import patch

import pytest
from typer.testing import CliRunner

from parallax.cli import app

runner = CliRunner()

_REFINEMENT_BLOCK = (
    "<!-- PARALLAX REFINEMENT: Auto-generated by `parallax init`.\n"
    "Start a Claude Code session and ask Claude to read "
    "CLAUDE.md, PARALLAX.md,\n"
    "and CONSTITUTION.md, then propose edits for project "
    "cohesion in plan mode.\n"
    "Iterate until satisfied, then run "
    "`parallax refine --done` to remove this block. -->\n"
    "\n"
)


class TestRefineInteractive:
    def test_no_flag_launches_interactive(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.chdir(tmp_path)
        with patch("parallax.cli.run_refinement", return_value=True) as mock_refine:
            result = runner.invoke(app, ["refine"])
        assert result.exit_code == 0
        mock_refine.assert_called_once_with(tmp_path, merge_mode=False)

    def test_target_dir(self, tmp_path: Path) -> None:
        with patch("parallax.cli.run_refinement", return_value=True) as mock_refine:
            result = runner.invoke(app, ["refine", "-t", str(tmp_path)])
        assert result.exit_code == 0
        mock_refine.assert_called_once_with(tmp_path, merge_mode=False)

    def test_detects_merge_guide(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.chdir(tmp_path)
        guide_dir = tmp_path / ".parallax"
        guide_dir.mkdir()
        (guide_dir / "merge-guide.md").write_text("# Merge Guide\n")

        with patch("parallax.cli.run_refinement", return_value=True) as mock_refine:
            result = runner.invoke(app, ["refine"])
        assert result.exit_code == 0
        assert "Merge guide detected" in result.output
        mock_refine.assert_called_once_with(tmp_path, merge_mode=True)


class TestRefineDone:
    def test_strips_blocks(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.chdir(tmp_path)

        claude_md = tmp_path / "CLAUDE.md"
        parallax_md = tmp_path / "PARALLAX.md"
        claude_md.write_text(_REFINEMENT_BLOCK + "# Project\n\nContent here.\n")
        parallax_md.write_text(_REFINEMENT_BLOCK + "# Workflow\n\nRules.\n")

        result = runner.invoke(app, ["refine", "--done"])
        assert result.exit_code == 0
        assert "Stripped" in result.output

        # Verify blocks removed
        assert "PARALLAX REFINEMENT" not in claude_md.read_text()
        assert "PARALLAX REFINEMENT" not in parallax_md.read_text()
        # Verify content preserved
        assert "# Project" in claude_md.read_text()
        assert "# Workflow" in parallax_md.read_text()

    def test_done_with_target_dir(self, tmp_path: Path) -> None:
        claude_md = tmp_path / "CLAUDE.md"
        claude_md.write_text(_REFINEMENT_BLOCK + "# Project\n")
        result = runner.invoke(app, ["refine", "--done", "-t", str(tmp_path)])
        assert result.exit_code == 0
        assert "PARALLAX REFINEMENT" not in claude_md.read_text()

    def test_no_blocks_found(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.chdir(tmp_path)
        result = runner.invoke(app, ["refine", "--done"])
        assert result.exit_code == 0
        assert "No refinement blocks found" in result.output

    def test_only_one_file_has_block(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.chdir(tmp_path)
        claude_md = tmp_path / "CLAUDE.md"
        claude_md.write_text(_REFINEMENT_BLOCK + "# Project\n")

        result = runner.invoke(app, ["refine", "--done"])
        assert result.exit_code == 0
        assert "1 file(s)" in result.output

    def test_unpaired_marker_exits_1(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.chdir(tmp_path)
        # Start marker with no closing -->
        broken = "<!-- PARALLAX REFINEMENT: unclosed block\n# Content\n"
        (tmp_path / "CLAUDE.md").write_text(broken)

        result = runner.invoke(app, ["refine", "--done"])
        assert result.exit_code == 1
        assert "Unpaired" in result.output
