<!-- PARALLAX REFINEMENT: Auto-generated by `parallax init`.
Start a Claude Code session and ask Claude to read CLAUDE.md, PARALLAX.md,
and CONSTITUTION.md, then propose edits for project cohesion in plan mode.
Iterate until satisfied, then run `parallax refine --done` to remove this block. -->

# ${project_name} -- Developer Guide

Instructions for AI agents and humans building ${project_name}.

## Project Overview

**${summary}**

Scientific domain: ${domain}

## Tech Stack

- Primary language(s): ${languages}
- Package manager: ${package_manager}
- Test framework: ${test_framework}
${science_requirements_section}${preferred_patterns_section}${outlawed_patterns_section}${key_libraries_section}
## Code Conventions

- Type hints on all function signatures
- Loud errors: surface problems immediately, never swallow exceptions
- Concise, scientific tone in docs and comments
- No LLM-speak, no emojis
- Minimal sufficient complexity for current requirements
${units_rule}
## Scientific Rigor

- Hypotheses before implementation: know what you expect before writing code
- Test every feature; never weaken tests to pass
- Document negative results
- Reproducible environments
- See @CONSTITUTION.md for the full set of scientific values
${git_section}
## Writing Style

All docs, markdown, READMEs, commit messages, and code comments:
- Concise, scientific tone
- No LLM-speak ("I'd be happy to...", "Great question!", "Certainly!")
- No emojis

## Never Do

- Never reduce test tolerances/scope to make tests pass without explicit human approval
- Never swallow exceptions or hide error details
- Never commit .env, credentials, or secrets
- Never add emojis to code, docs, or commits
- Never skip type hints on function signatures

## References

- @CONSTITUTION.md -- core scientific values
- @PARALLAX.md -- scientific workflow rules
